site_name: Mongorunway
site_url: https://business-card/docs/
site_description: Mongorunway organization.
site_author: Animatea
copyright: >
  Copyright &copy; 2023 Animatea

theme:
  name: material
  logo: assets/mongorunway-icon.png
  favicon: assets/mongorunway-icon.png
  custom_dir: docs/overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
  palette:
    - scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/KKUFRZCt4f/
  alternate:
    - name: en - English
      link: /i18n/en/
      lang: en
    - name: uk - Українська мова
      link: /i18n/uk/
      lang: uk
    - name: cs - Český jazyk
      link: /i18n/cs/
      lang: cs
    - name: de - Deutsche Sprache
      link: /i18n/de/
      lang: de
    - name: es - Idioma español
      link: //i18n/es/
      lang: es
    - name: fr - Langue française
      link: /i18n/fr/
      lang: fr
    - name: ru - Русский язык
      link: /i18n/ru/
      lang: uk

extra_css:
  - stylesheets/slick-buttons.css

markdown_extensions:
  - markdown.extensions.attr_list
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: "¤"

nav:
  - "Homepage":
    - index.md
